MainTableView+NetworkOperations
Alexdive/PokemonList pull request #2
Opened 2021-04-20 02:29 UTC by Alexdive

2021-04-20 18:47 UTC, kliukin requested changes
1. Let's try to make smaller PRs.
2. Read some articles about MVVM approach (like https://www.toptal.com/ios/swift-tutorial-introduction-to-mvvm) and refine your solution. 
3. Since it's MVVM let's add some reactive binding. Maybe with Combine if it's possible.

2021-04-20 18:47 UTC, kliukin commented on PokemonList/MainTableVC/MainTableVCViewModel.swift
> +final class MainTableVCViewModel {
This VM should be closed with a protocol.

2021-04-20 18:47 UTC, kliukin commented on PokemonList/MainTableVC/MainTableVCViewModel.swift
> +    func getPokemon(with indexPath: IndexPath, completion: @escaping ((Pokemon) -> Void)) {
Let's break down this method as well.

2021-04-20 18:47 UTC, kliukin commented on PokemonList/MainTableVC/MainTableViewController.swift
> +final class MainTableViewController: UIViewController {
This view should be closed with a protocol.

2021-04-20 18:47 UTC, kliukin commented on PokemonList/MainTableVC/MainTableVCViewModel.swift
> +import UIKit
Normally you don't want to use UIKit classes in VMs.

2021-04-20 18:47 UTC, kliukin commented on PokemonList/MainTableVC/MainTableVCViewModel.swift
> +            let downloadOp = NetworkDataOperation(url: url) { [weak self] result in
Also your VM should be injected with dependencies via init. 
Something like:
`init(cacher: CacherProtocol, networkManager: NetworkManagerProtocol)`

2021-04-20 18:47 UTC, kliukin commented on PokemonList/MainTableVC/MainTableViewController.swift
> +    let startUrlString = "https://pokeapi.co/api/v2/pokemon"
The view should not have this data.

The responsibilities of you views are:
1) Show UI for data from VM
2) Handle users interactions

2021-04-21 02:33 UTC, Alexdive commented on PokemonList/Cache.swift
> +struct Cache {
No idea :(

2021-04-21 02:34 UTC, Alexdive commented on PokemonList/MainTableVC/MainTableVCViewModel.swift
> +import UIKit
How to return downloaded image then?

2021-04-21 03:53 UTC, Alexdive commented
Combine won't work if our target is ios11

2021-04-22 07:38 UTC, merged