Feature/realm cache
Alexdive/PokemonList pull request #7
Opened 2021-05-14 18:34 UTC by Alexdive

Changed realization of SVG downloading and decoding using another pod.
added realm in memory cache.

2021-05-17 06:58 UTC, kliukin requested changes

2021-05-17 06:58 UTC, kliukin commented on PokemonList/Cache/RealmDataProvider.swift
> +        if let pokemon = object as? Pokemon {
What if we decided to store another object in cache? Is it going to be another if statement? 
It's a violation of O in Solid.

2021-05-17 06:58 UTC, kliukin commented on PokemonList/Cache/RealmDataProvider.swift
> +        if Object.self == Pokemon.self {
Same here

2021-05-17 06:58 UTC, kliukin commented on PokemonList/DetailsVC/DetailsViewController.swift
>      var pokemon: Pokemon
We should create a VM for Details View.

2021-05-17 06:58 UTC, kliukin commented on PokemonList/DetailsVC/DetailsViewController.swift
> +    init(forPokemon: Pokemon, pokemonImage: UIImage) {
Just 'pokemon' instaead of 'forPokemon' would sound better.

2021-05-17 06:58 UTC, kliukin commented on PokemonList/DetailsVC/DetailsViewController.swift
>      let reuseId = "StatsCell"
We should create a cell where this data should be stored.

2021-05-17 06:58 UTC, kliukin commented on PokemonList/DetailsVC/DetailsViewController.swift
>          heightLabel.text = "Height: \(pokemon.height)"
Text should come from a VM.

2021-05-17 06:58 UTC, kliukin commented on PokemonList/Common/SceneDelegate.swift
> +//        previous cache realization with NSCache
No commented code should be committed. 
The deleted code will still be available in Git in case we need it.

2021-05-17 06:58 UTC, kliukin commented on PokemonList/Cache/RealmDataProvider.swift
> +import Foundation
RealmSwift already imports Foundation. So it can be omitted.

2021-05-17 06:58 UTC, kliukin commented on PokemonList/Cache/RealmDataProvider.swift
> +
Let's not make this additional empty line in the beginnings of classes and functions.

2021-05-17 06:58 UTC, kliukin commented on PokemonList/Cache/RealmDataProvider.swift
> +            DispatchQueue.main.async {
Why do you use the main queue for write operations?

2021-05-17 06:58 UTC, kliukin commented on PokemonList/MainTableVC/MainTableViewController.swift
>                  cell?.setName(name: pokemon.name)
Why this one is not in the main queue?

2021-05-17 06:58 UTC, kliukin commented on PokemonList/MainTableVC/MainTableViewController.swift
> +                self.viewModel.getImageData(pokemon: pokemon, indexPath: indexPath) { data in
Why is this non-UI operation in the main queue?

2021-05-20 18:12 UTC, kliukin requested changes
Please answer 'Done' on comments if you've fixed it.

2021-05-20 18:12 UTC, kliukin commented on PokemonList/Cache/RealmDataProvider.swift
> +    }()
Making this a computed property solves the problem with the 'wrong queue' crash.

2021-05-20 18:12 UTC, kliukin commented on PokemonList/Cache/RealmDataProvider.swift
> +        autoreleasepool {
Why do you need to call this?

2021-05-21 06:45 UTC, Alexdive commented on PokemonList/Cache/RealmDataProvider.swift
> +        if let pokemon = object as? Pokemon {
Kinda done, but not really perfect

2021-05-21 06:45 UTC, Alexdive commented on PokemonList/Cache/RealmDataProvider.swift
> +        if Object.self == Pokemon.self {
Kinda done, but not really perfect

2021-05-21 06:47 UTC, Alexdive commented on PokemonList/DetailsVC/DetailsViewController.swift
>      let reuseId = "StatsCell"
What do you mean? Didn't really get you.

2021-05-21 06:47 UTC, Alexdive commented on PokemonList/Cache/RealmDataProvider.swift
> +import Foundation
Done

2021-05-21 06:47 UTC, Alexdive commented on PokemonList/Cache/RealmDataProvider.swift
> +
Noted

2021-05-21 06:54 UTC, Alexdive commented on PokemonList/Cache/RealmDataProvider.swift
> +        autoreleasepool {
The intermediate versions of data in the Realm file cannot be reused until the RLMRealm object is deallocated. To avoid this issue, you should use an explicit autorelease pool when accessing a Realm from a dispatch queue.

from realm documentation

2021-05-25 05:49 UTC, merged