added favorites tab
Alexdive/PokemonList pull request #8
Opened 2021-05-25 05:49 UTC by Alexdive

Not yet implemented view model for details view

2021-05-26 06:48 UTC, kliukin requested changes

2021-05-26 06:48 UTC, kliukin commented on PokemonList/DataProvider/RealmDataBase.swift
> +}
Let's separate Cache from Persistance.

2021-05-26 06:48 UTC, kliukin commented on PokemonList/DataProvider/RealmDataBase.swift
> +    }
You know, this approach doesn't look good. 
Let's try and create a storage manager for each type we'd like to store. Maybe something like this:

<img width="828" alt="Screenshot 2021-05-26 at 09 40 59" src="https://user-images.githubusercontent.com/24508036/119614039-7cee3800-be06-11eb-89f8-f27e97a43898.png">

2021-05-26 06:48 UTC, kliukin commented on PokemonList/DetailsVC/DetailsViewController.swift
> +    var isFavorite: Bool! {
This logic should go to VM when it's created.

2021-05-26 07:57 UTC, Alexdive commented on PokemonList/TabBar.swift
> +import Foundation
my bad

2021-05-26 07:59 UTC, Alexdive commented on PokemonList/TabBar.swift
> +    var favoritePokemonsVCViewModel: FavoritePokemonsViewModel!
I was experimenting with declaring DB on different levels. Gonna move it back to setupVC method

2021-05-26 07:59 UTC, Alexdive commented on PokemonList/BaseTableVC.swift
> +class BaseTableVC: UIViewController {
noted

2021-05-26 07:59 UTC, Alexdive commented on PokemonList/DataProvider/RealmDataBase.swift
> +}
will do it!

2021-05-26 08:00 UTC, Alexdive commented on PokemonList/DataProvider/RealmDataBase.swift
> +    }
sounds good

2021-05-26 08:00 UTC, Alexdive commented on PokemonList/DetailsVC/DetailsViewController.swift
> +    var isFavorite: Bool! {
that was the plan ;)

2021-05-27 14:17 UTC, kliukin commented on PokemonList/BaseTableVC.swift
By the way, you don't have to excuse yourself in PR comments. If you agree with a comment it would be enough to write: "Done".
@Alexdive

2021-05-27 15:07 UTC, kliukin requested changes

2021-05-27 15:07 UTC, kliukin commented on PokemonList/DetailsVC/DetailsViewController.swift
>      @objc private func onHeartBtn() {
Actions are usually named in this pattern: on[Button's name]Tapped() or didTap[Button's name].

2021-05-27 15:07 UTC, kliukin commented on PokemonList/DetailsVC/DetailsViewController.swift
> +        let heartImage = viewModel.isFavorite() ? UIImage(systemName: "heart.fill") : UIImage(systemName: "heart")
Logic should be in VC.

2021-05-27 15:07 UTC, kliukin commented on PokemonList/DetailsVC/DetailsViewController.swift
>      }
Better move inside a cell.

2021-05-27 15:07 UTC, kliukin commented on PokemonList/FavoritePokemonVC/FavoritePokemonsViewModel.swift
> +    var pokemonStorage: PokemonPersistable
Why not let?

2021-05-27 15:07 UTC, kliukin commented on PokemonList/FavoritePokemonVC/FavoritePokemonsViewModel.swift
> +    var pokemonStorage: PokemonPersistable
Plus, I guess these should be private.

2021-05-27 15:07 UTC, kliukin commented on PokemonList/FavoritePokemonVC/FavoritePokemonsViewModel.swift
> +        imageDataStorage.getAllRealmImageData { [weak self] realmImagesData in
An empty line before this needed.

2021-05-27 15:07 UTC, kliukin commented on PokemonList/FavoritePokemonVC/FavoritePokemonsViewModel.swift
> +
And this one is not needed.

2021-05-27 15:07 UTC, kliukin commented on PokemonList/FavoritePokemonVC/FavoritePokemonsViewModel.swift
> +    func endDisplaying(at indexPath: IndexPath) {}
Why do we need an empty implementation?

2021-05-27 15:07 UTC, kliukin commented on PokemonList/Models/RealmDataModel.swift
> +@objcMembers class RealmImageData: Object {
I would put 'Realm' at the end of names.

2021-05-27 15:07 UTC, kliukin commented on PokemonList/TabBar.swift
> +
Extra empty line.

2021-05-28 06:10 UTC, Alexdive commented on PokemonList/BasePokemonTableVC.swift
>  // MARK: - Table view data source
done

2021-05-28 06:15 UTC, Alexdive commented on PokemonList/BasePokemonTableVC.swift
>          if isLoadingCell(for: indexPath) {
renamed to isCellToDownload

2021-05-28 06:32 UTC, Alexdive commented on PokemonList/Constants/Constants.swift
> +    static let statsTableViewCellID = "StatsCell"
I'm using default tableViewCell, so no separate class there

2021-05-28 06:46 UTC, Alexdive commented on PokemonList/BasePokemonTableVC.swift
> +                cell.setName(name: pokemon.name)
done

2021-05-28 06:49 UTC, Alexdive commented on PokemonList/BasePokemonTableVC.swift
> +        configureAndShowDetailsVC(indexPath)
noted and done

2021-05-28 06:49 UTC, Alexdive commented on PokemonList/BasePokemonTableVC.swift
> +            if let last = viewModel.lastListUrl {
done

2021-05-28 06:49 UTC, Alexdive commented on PokemonList/DataProvider/ImageDataStorage.swift
> +protocol ImageDataPersistable {
noted and done

2021-05-28 06:50 UTC, Alexdive commented on PokemonList/DataProvider/ImageDataStorage.swift
> +            print("Something went wrong: \(error.localizedDescription)")
I guess we can leave it as is, since we didn't introduce error displaying yet

2021-05-28 06:51 UTC, Alexdive commented on PokemonList/DataProvider/PokemonStorage.swift
> +    func delete(pokemonWithId key: String)
that was my attempt to make code more self-explanatory, because we have 2 sets of similar signatures in different classes

2021-05-28 06:52 UTC, Alexdive commented on PokemonList/DataProvider/PokemonStorage.swift
> +    var onDataBaseChange: (() -> Void)? { get set }
What is wrong with this callback? It alerts view model that we have changes in DB

2021-05-28 06:52 UTC, Alexdive commented on PokemonList/DataProvider/RealmCacheProvider.swift
> +protocol DataManagerProtocol {
done

2021-05-28 06:53 UTC, Alexdive commented on PokemonList/DetailsVC/DetailsViewController.swift
>      @objc private func onHeartBtn() {
done

2021-05-28 06:53 UTC, Alexdive commented on PokemonList/DetailsVC/DetailsViewController.swift
> +        let heartImage = viewModel.isFavorite() ? UIImage(systemName: "heart.fill") : UIImage(systemName: "heart")
didn't get you

2021-05-28 06:54 UTC, Alexdive commented on PokemonList/DetailsVC/DetailsViewController.swift
>      }
I'm using native UITableViewCell, not custom class here

2021-05-28 06:56 UTC, Alexdive commented on PokemonList/FavoritePokemonVC/FavoritePokemonsViewModel.swift
> +    var pokemonStorage: PokemonPersistable
var because I'm redefining callback
private done

2021-05-28 06:56 UTC, Alexdive commented on PokemonList/FavoritePokemonVC/FavoritePokemonsViewModel.swift
> +        imageDataStorage.getAllRealmImageData { [weak self] realmImagesData in
done

2021-05-28 06:56 UTC, Alexdive commented on PokemonList/FavoritePokemonVC/FavoritePokemonsViewModel.swift
> +
done

2021-05-28 06:58 UTC, Alexdive commented on PokemonList/FavoritePokemonVC/FavoritePokemonsViewModel.swift
> +    func endDisplaying(at indexPath: IndexPath) {}
protocol method, otherwise need to introduce another VC for favourite pokemons and another protocol for VM

2021-05-28 06:58 UTC, Alexdive commented on PokemonList/Models/RealmDataModel.swift
> +@objcMembers class RealmImageData: Object {
done

2021-05-28 06:58 UTC, Alexdive commented on PokemonList/TabBar.swift
> +
done

2021-05-31 08:05 UTC, merged