refactor networking
Alexdive/PokemonList pull request #9
Opened 2021-06-01 09:53 UTC by Alexdive

2021-06-07 06:56 UTC, kliukin requested changes

2021-06-07 06:56 UTC, kliukin commented on PokemonList/BasePokemonTableVC.swift
> +    var isSeachBarAnimationCompleted: Bool = false
Looks like you don't use this one.

2021-06-07 06:56 UTC, kliukin commented on PokemonList/BasePokemonTableVC.swift
> +            viewModel.searchPokemon(byName: text)
Usually there is some delay to allow users to type more characters before making a request.

2021-06-07 06:56 UTC, kliukin commented on PokemonList/DataProvider/ImageDataStorage.swift
> +    func save(imageData: Data?, withKey key: String)
I don't think passing an option is a good idea.

2021-06-07 06:56 UTC, kliukin commented on PokemonList/DataProvider/RealmCacheProvider.swift
> +    init?(object: Object) {
Empty line before.

2021-06-07 06:56 UTC, kliukin commented on PokemonList/BasePokemonTableVC.swift
> +    private func setupDetailsVC(pokemon: Pokemon, imageData: Data?) -> DetailsViewController {
Empty line before.

2021-06-07 06:56 UTC, kliukin commented on PokemonListTests/PokemonListTests.swift
> +    }
Tests are not working.

2021-06-07 06:56 UTC, kliukin commented on PokemonList/Network/NetworkManager.swift
> +    func cancelFetch(at indexPath: IndexPath)
'indexPath' is something UITableView related. Normally NetworkManager shouldn't know about this stuff.

2021-06-07 06:56 UTC, kliukin commented on PokemonList/Network/NetworkManager.swift
> +    }
This is a violation of O in Solid. If you need to fetch a 'Person' you will have to add 'parsePerson' and so on.

2021-06-09 06:36 UTC, Alexdive commented on PokemonList/BasePokemonTableVC.swift
> +    var isSeachBarAnimationCompleted: Bool = false
deleted

2021-06-09 06:36 UTC, Alexdive commented on PokemonList/DataProvider/RealmCacheProvider.swift
> +    init?(object: Object) {
done

2021-06-09 06:36 UTC, Alexdive commented on PokemonList/BasePokemonTableVC.swift
> +    private func setupDetailsVC(pokemon: Pokemon, imageData: Data?) -> DetailsViewController {
done

2021-06-09 06:36 UTC, Alexdive commented on PokemonList/Network/NetworkManager.swift
> +    func cancelFetch(at indexPath: IndexPath)
refactored

2021-06-09 06:37 UTC, Alexdive commented on PokemonList/Network/NetworkManager.swift
> +    }
refactored

2021-06-09 06:37 UTC, Alexdive commented on PokemonListTests/PokemonListTests.swift
> +    }
in progress

2021-06-09 06:45 UTC, Alexdive commented on PokemonList/DataProvider/ImageDataStorage.swift
> +    func save(imageData: Data?, withKey key: String)
fixed

2021-06-14 15:44 UTC, kliukin requested changes

2021-06-14 15:44 UTC, kliukin commented on PokemonList/DetailsVC/DetailsVCViewModel.swift
> +    private func addToFavorites() {
It would be clearer to pass a currently selected pokemon as a func parameter.

2021-06-14 15:44 UTC, kliukin commented on PokemonList/DetailsVC/DetailsVCViewModel.swift
> +    private func removeFromFavorites() {
It would be clearer to pass a currently selected pokemon as a func parameter.

2021-06-14 15:44 UTC, kliukin commented on PokemonList/DetailsVC/DetailsViewController.swift
> +            self.presentationObject = self.viewModel.getPresentationObject()
Why do we assign new presentation object when the toggle is switched?

2021-06-14 15:44 UTC, kliukin commented on PokemonList/DetailsVC/DetailsViewController.swift
> +        }
`pokemonImageView.image = presentationObject.image  ?? UIImage(systemName: "photo")`

2021-06-14 15:44 UTC, kliukin commented on PokemonList/FavoritePokemonVC/FavoritePokemonsViewModel.swift
> +        imageDataStorage.getAllRealmImageData { [unowned self] realmImagesData in
If we declare this func in our ImageDataStorage protocol it means that it has a Realm dependency. This is exactly what we are trying to avoid by using protocols.

2021-06-14 15:44 UTC, kliukin commented on PokemonList/FavoritePokemonVC/FavoritePokemonsViewModel.swift
> +    var tableViewCellsCount: Int {
I don't think that a VM should have something related to table view.

2021-06-14 15:44 UTC, kliukin commented on PokemonList/FavoritePokemonVC/FavoritePokemonsViewModel.swift
> +    func getLinksList() {
This name doesn't actually say what the func really does.

2021-06-14 15:44 UTC, kliukin commented on PokemonList/FavoritePokemonVC/FavoritePokemonsViewModel.swift
> +            })
I think we shouldn't use IndexPath in VMs.

2021-06-14 15:44 UTC, kliukin commented on PokemonList/Network/NetworkManager.swift
> +    func cancelFetch(at index: Int)
It'd be better to use some id instead on an index here.

2021-06-14 15:44 UTC, kliukin commented on PokemonList/Network/NetworkManager.swift
> +    func cancelFetch(at index: Int)
Maybe URL or a pokemon's id.

2021-06-14 15:44 UTC, kliukin commented on PokemonList/PokemonListTableVC/PokemonListTableVCViewModel.swift
>  protocol PokemonTableVCViewModelDelegate: class {
I think 'VC' could be omitted here.

2021-06-14 15:44 UTC, kliukin commented on PokemonList/PokemonListTableVC/PokemonListTableVCViewModel.swift
>      }
This could be moved to Network Manager.

2021-06-14 15:44 UTC, kliukin commented on PokemonList/PokemonListTableVC/PokemonListTableVCViewModel.swift
> +            return nil
This code is duplicated.

2021-06-14 15:44 UTC, kliukin commented on PokemonList/PokemonListTableVC/PokemonListTableVCViewModel.swift
>              }
Duplicated as well.

2021-06-15 12:19 UTC, Alexdive commented on PokemonList/BasePokemonTableVC.swift
> +    private lazy var presentationObject = viewModel.getPresentationObject()
done

2021-06-15 12:19 UTC, Alexdive commented on PokemonList/BasePokemonTableVC.swift
> +    var timer: Timer?
done

2021-06-15 12:19 UTC, Alexdive commented on PokemonList/BasePokemonTableVC.swift
>      private lazy var tableView: UITableView = {
done

2021-06-15 12:20 UTC, Alexdive commented on PokemonList/BasePokemonTableVC.swift
>          cell.clearUI()
both options are ok

2021-06-15 12:23 UTC, Alexdive commented on PokemonList/BasePokemonTableVC.swift
>      }
otherwise there is some extra space on top of table view

2021-06-15 12:23 UTC, Alexdive commented on PokemonList/BasePokemonTableVC.swift
>      }
same

2021-06-15 17:04 UTC, Alexdive commented on PokemonList/DetailsVC/DetailsVCViewModel.swift
> +    private func addToFavorites() {
done

2021-06-15 17:04 UTC, Alexdive commented on PokemonList/DetailsVC/DetailsVCViewModel.swift
> +    private func removeFromFavorites() {
done

2021-06-15 17:05 UTC, Alexdive commented on PokemonList/DetailsVC/DetailsViewController.swift
> +            self.presentationObject = self.viewModel.getPresentationObject()
cleared

2021-06-15 17:05 UTC, Alexdive commented on PokemonList/DetailsVC/DetailsViewController.swift
> +        }
good point! Done

2021-06-16 07:31 UTC, Alexdive commented on PokemonList/FavoritePokemonVC/FavoritePokemonsViewModel.swift
> +    var tableViewCellsCount: Int {
renamed

2021-06-16 07:32 UTC, Alexdive commented on PokemonList/FavoritePokemonVC/FavoritePokemonsViewModel.swift
> +            })
renamed

2021-06-16 07:34 UTC, Alexdive commented on PokemonList/PokemonListTableVC/PokemonListTableVCViewModel.swift
>  protocol PokemonTableVCViewModelDelegate: class {
ok

2021-06-16 07:34 UTC, Alexdive commented on PokemonList/PokemonListTableVC/PokemonListTableVCViewModel.swift
>      }
done

2021-06-16 07:35 UTC, Alexdive commented on PokemonList/PokemonListTableVC/PokemonListTableVCViewModel.swift
> +            return nil
made an extension to UIImage

2021-06-16 07:46 UTC, Alexdive commented on PokemonList/FavoritePokemonVC/FavoritePokemonsViewModel.swift
> +        imageDataStorage.getAllRealmImageData { [unowned self] realmImagesData in
fixed

2021-06-21 16:13 UTC, Alexdive commented on PokemonList/BasePokemonTableVC.swift
> +            self.navigationController?.pushViewController(detaisVC, animated: true)
added activity indicator

2021-06-22 10:23 UTC, kliukin requested changes

2021-06-22 10:23 UTC, kliukin commented on PokemonList/PokemonListTableVC/PokemonListTableVCViewModel.swift
> +class PokemonSearch {
I have doubts about the name of this class. It sounds a little bit misleading. The name implies that this class can be used to actually search for pokemons.
 
We want this class to be able to add a delay for a closure, so we can make it more generic:

<img width="797" alt="Screenshot 2021-06-22 at 13 01 52" src="https://user-images.githubusercontent.com/24508036/122905680-194e2080-d35a-11eb-8278-8a563c7e56fe.png">

2021-06-22 10:23 UTC, kliukin commented on PokemonList/PokemonListTableVC/PokemonListTableVCViewModel.swift
> +        networkManager.fetch(request: .primary) { [weak self] list in
'primary' name doesn't say what it fetches.

2021-06-22 10:23 UTC, kliukin commented on PokemonList/PokemonListTableVC/PokemonListTableVC.swift
> +//        viewModel.delegate = self
Commented out code shouldn't appear in PRs.

2021-06-22 10:23 UTC, kliukin commented on PokemonList/PokemonListTableVC/MainTableViewCell.swift
> +    }
Empty line after.

2021-06-22 10:23 UTC, kliukin commented on PokemonList/PokemonListTableVC/MainTableViewCell.swift
> +    }
Empty line after.

2021-06-22 10:23 UTC, kliukin commented on PokemonList/Network/NetworkManager.swift
> +    func fetch(request: FetchRequest, completion: @escaping (Any) -> Void) {
Can we make this func generic? So it could work with any Codable type.

2021-06-22 14:54 UTC, Alexdive commented on PokemonList/Network/NetworkManager.swift
> +    func fetch(request: FetchRequest, completion: @escaping (Any) -> Void) {
Done

2021-06-22 14:54 UTC, Alexdive commented on PokemonList/PokemonListTableVC/MainTableViewCell.swift
> +    }
done

2021-06-22 14:55 UTC, Alexdive commented on PokemonList/PokemonListTableVC/MainTableViewCell.swift
> +    }
done

2021-06-22 14:55 UTC, Alexdive commented on PokemonList/PokemonListTableVC/PokemonListTableVC.swift
> +//        viewModel.delegate = self
done

2021-06-22 14:55 UTC, Alexdive commented on PokemonList/PokemonListTableVC/PokemonListTableVCViewModel.swift
> +        networkManager.fetch(request: .primary) { [weak self] list in
changed

2021-06-22 21:51 UTC, Alexdive commented on PokemonList/PokemonListTableVC/PokemonListTableVCViewModel.swift
> +class PokemonSearch {
renamed and kept implementation with checking the string

2021-06-22 21:53 UTC, merged